### ISSUE TITLE
Creating basic frontend structure using react tailwind and vite 

### ISSUE THREAD

**Issue by Vdcds** [thedemonsid/personal-leetcode#13]
This issue pertains to setting up the fundamental frontend structure for the project using React, Tailwind CSS, and Vite.

##Objective:
Integrate React as the primary frontend library for building dynamic user interfaces.
Utilize Tailwind CSS for rapid and efficient styling, enabling a consistent and responsive design across the application.
Employ Vite as the build tool for fast development and optimized production builds.
##Tasks:
Initialize a new React project with Vite.
Integrate Tailwind CSS into the project configuration.
Set up basic components and layouts for the frontend structure.
Configure routing if necessary for navigation within the application.
Ensure compatibility and responsiveness across various screen sizes.
Test the setup thoroughly to confirm functionality and appearance.

**Comment by Vdcds** [comment]
will be working on this

**Comment by thedemonsid** [comment]
hmm
lets see how good are you

**Comment by Vdcds** [comment]
close the issue please
